[project]
name = "langchain-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Praveen Chandran", email = "praveen.chandran81@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain-google-genai>=4.4.0",
    "python-dotenv>=1.2.4",
]

[project.scripts]
langchain-poc = "langchain_poc:main"

[build-system]
requires = ["uv_build>=0.12.24,<0.13.0"]
build-backend = "uv_build"
